// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthInfo() {
  return window['go']['main']['App']['AuthInfo']();
}

export function DefaultOutputDir() {
  return window['go']['main']['App']['DefaultOutputDir']();
}

export function DeviceConnected() {
  return window['go']['main']['App']['DeviceConnected']();
}

export function Download(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3, arg4);
}

export function InstallIPA(arg1) {
  return window['go']['main']['App']['InstallIPA'](arg1);
}

export function InvalidateSignedInDSID() {
  return window['go']['main']['App']['InvalidateSignedInDSID']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListInstalledApps() {
  return window['go']['main']['App']['ListInstalledApps']();
}

export function ListVersions(arg1) {
  return window['go']['main']['App']['ListVersions'](arg1);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function LookupArtwork(arg1) {
  return window['go']['main']['App']['LookupArtwork'](arg1);
}

export function PickIPAPath() {
  return window['go']['main']['App']['PickIPAPath']();
}

export function PickOutputDir() {
  return window['go']['main']['App']['PickOutputDir']();
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SignedInDSID() {
  return window['go']['main']['App']['SignedInDSID']();
}

export function SwitchAccount(arg1) {
  return window['go']['main']['App']['SwitchAccount'](arg1);
}
