// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AuthInfo():Promise<main.AuthInfo>;

export function DefaultOutputDir():Promise<string>;

export function DeviceConnected():Promise<boolean>;

export function Download(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<main.DownloadResult>;

export function InstallIPA(arg1:string):Promise<main.InstallResult>;

export function InvalidateSignedInDSID():Promise<void>;

export function ListInstalledApps():Promise<Array<main.InstalledApp>>;

export function ListVersions(arg1:string):Promise<Array<main.Version>>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<main.LoginResult>;

export function Logout():Promise<void>;

export function LookupArtwork(arg1:Array<main.ArtworkRequest>):Promise<Record<string, string>>;

export function PickIPAPath():Promise<string>;

export function PickOutputDir():Promise<string>;

export function Search(arg1:string,arg2:number):Promise<main.SearchResponse>;

export function SignedInDSID():Promise<string>;
